
/**
 * KPwBI (Kantor Perwakilan Bank Indonesia) office locations across Indonesia.
 * 46 offices grouped by Wilayah Koordinasi (coordination region).
 * Offices marked isKorwil=true are regional coordinator offices (shown with bigger markers).
 */
export interface KpwbiOffice {
  id: string;
  name: string;
  city: string;
  provinceId: string;
  latitude: number;
  longitude: number;
  region: string;
  isKorwil: boolean;
  isKantorPusat?: boolean;
  category: 'kpw' | 'korwil' | 'kantor_pusat' | 'dc' | 'drc';
}

export const KPWBI_OFFICES: KpwbiOffice[] = [
  // ═══════════════════════════════════════════════════════
  // Wilayah Koordinasi Sumatera (Korwil: Medan)
  // ═══════════════════════════════════════════════════════
  {
    id: 'kpwbi-banda-aceh',
    name: 'KPwBI Provinsi Aceh',
    city: 'Banda Aceh',
    provinceId: 'ID-AC',
    latitude: 5.5562,
    longitude: 95.3184,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-lhokseumawe',
    name: 'KPwBI Lhokseumawe',
    city: 'Lhokseumawe',
    provinceId: 'ID-AC',
    latitude: 5.1764,
    longitude: 97.1432,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-medan',
    name: 'KPwBI Provinsi Sumatera Utara',
    city: 'Medan',
    provinceId: 'ID-SU',
    latitude: 3.5902,
    longitude: 98.6775,
    region: 'Sumatera',
    isKorwil: true,
    category: 'korwil',
  },
  {
    id: 'kpwbi-pematangsiantar',
    name: 'KPwBI Pematangsiantar',
    city: 'Pematangsiantar',
    provinceId: 'ID-SU',
    latitude: 2.9602,
    longitude: 99.0621,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-sibolga',
    name: 'KPwBI Sibolga',
    city: 'Sibolga',
    provinceId: 'ID-SU',
    latitude: 1.7371,
    longitude: 98.7845,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-padang',
    name: 'KPwBI Provinsi Sumatera Barat',
    city: 'Padang',
    provinceId: 'ID-SB',
    latitude: -0.9427,
    longitude: 100.3608,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-pekanbaru',
    name: 'KPwBI Provinsi Riau',
    city: 'Pekanbaru',
    provinceId: 'ID-RI',
    latitude: 0.5186,
    longitude: 101.4468,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-batam',
    name: 'KPwBI Provinsi Kepulauan Riau',
    city: 'Batam',
    provinceId: 'ID-KR',
    latitude: 1.1278,
    longitude: 104.0559,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-jambi',
    name: 'KPwBI Provinsi Jambi',
    city: 'Jambi',
    provinceId: 'ID-JA',
    latitude: -1.5947,
    longitude: 103.6143,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-bengkulu',
    name: 'KPwBI Provinsi Bengkulu',
    city: 'Bengkulu',
    provinceId: 'ID-BE',
    latitude: -3.8055,
    longitude: 102.2690,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-palembang',
    name: 'KPwBI Provinsi Sumatera Selatan',
    city: 'Palembang',
    provinceId: 'ID-SS',
    latitude: -2.9818,
    longitude: 104.7460,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-pangkalpinang',
    name: 'KPwBI Provinsi Kepulauan Bangka Belitung',
    city: 'Pangkalpinang',
    provinceId: 'ID-BB',
    latitude: -2.1226,
    longitude: 106.1087,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-bandar-lampung',
    name: 'KPwBI Provinsi Lampung',
    city: 'Bandar Lampung',
    provinceId: 'ID-LA',
    latitude: -5.4372,
    longitude: 105.2638,
    region: 'Sumatera',
    isKorwil: false,
    category: 'kpw',
  },

  // ═══════════════════════════════════════════════════════
  // Wilayah Koordinasi Jawa (Korwil: Kediri)
  // ═══════════════════════════════════════════════════════
  {
    id: 'kpwbi-jakarta',
    name: 'Bank Indonesia Kantor Pusat',
    city: 'Jakarta Pusat (Thamrin)',
    provinceId: 'ID-JK',
    latitude: -6.1823,
    longitude: 106.8216,
    region: 'Jawa',
    isKorwil: false,
    isKantorPusat: true,
    category: 'kantor_pusat',
  },
  {
    id: 'kpwbi-jakarta-kpw',
    name: 'KPwBI Provinsi DKI Jakarta',
    city: 'Jakarta Pusat (Senen)',
    provinceId: 'ID-JK',
    latitude: -6.1770,
    longitude: 106.8373,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-bandung',
    name: 'KPwBI Provinsi Jawa Barat',
    city: 'Bandung',
    provinceId: 'ID-JB',
    latitude: -6.9172,
    longitude: 107.6105,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-cirebon',
    name: 'KPwBI Cirebon',
    city: 'Cirebon',
    provinceId: 'ID-JB',
    latitude: -6.7171,
    longitude: 108.5670,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-tasikmalaya',
    name: 'KPwBI Tasikmalaya',
    city: 'Tasikmalaya',
    provinceId: 'ID-JB',
    latitude: -7.3241,
    longitude: 108.2227,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-serang',
    name: 'KPwBI Provinsi Banten',
    city: 'Serang',
    provinceId: 'ID-BT',
    latitude: -6.1171,
    longitude: 106.1557,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-semarang',
    name: 'KPwBI Provinsi Jawa Tengah',
    city: 'Semarang',
    provinceId: 'ID-JT',
    latitude: -6.9931,
    longitude: 110.4208,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-solo',
    name: 'KPwBI Solo / Surakarta',
    city: 'Solo',
    provinceId: 'ID-JT',
    latitude: -7.5714,
    longitude: 110.8291,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-purwokerto',
    name: 'KPwBI Purwokerto',
    city: 'Purwokerto',
    provinceId: 'ID-JT',
    latitude: -7.4239,
    longitude: 109.2315,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-tegal',
    name: 'KPwBI Tegal',
    city: 'Tegal',
    provinceId: 'ID-JT',
    latitude: -6.8665,
    longitude: 109.1352,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-yogyakarta',
    name: 'KPwBI DI Yogyakarta',
    city: 'Yogyakarta',
    provinceId: 'ID-YO',
    latitude: -7.8016,
    longitude: 110.3663,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-surabaya',
    name: 'KPwBI Provinsi Jawa Timur',
    city: 'Surabaya',
    provinceId: 'ID-JI',
    latitude: -7.2473,
    longitude: 112.7380,
    region: 'Jawa',
    isKorwil: true,
    category: 'korwil',
  },
  {
    id: 'kpwbi-malang',
    name: 'KPwBI Malang',
    city: 'Malang',
    provinceId: 'ID-JI',
    latitude: -7.9812,
    longitude: 112.6306,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-kediri',
    name: 'KPwBI Kediri',
    city: 'Kediri',
    provinceId: 'ID-JI',
    latitude: -7.8189,
    longitude: 112.0125,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-jember',
    name: 'KPwBI Jember',
    city: 'Jember',
    provinceId: 'ID-JI',
    latitude: -8.1725,
    longitude: 113.6934,
    region: 'Jawa',
    isKorwil: false,
    category: 'kpw',
  },

  // ═══════════════════════════════════════════════════════
  // Wilayah Koordinasi Kalimantan (Korwil: Banjarmasin)
  // ═══════════════════════════════════════════════════════
  {
    id: 'kpwbi-pontianak',
    name: 'KPwBI Provinsi Kalimantan Barat',
    city: 'Pontianak',
    provinceId: 'ID-KB',
    latitude: -0.0242,
    longitude: 109.3424,
    region: 'Kalimantan',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-palangka-raya',
    name: 'KPwBI Provinsi Kalimantan Tengah',
    city: 'Palangka Raya',
    provinceId: 'ID-KT',
    latitude: -2.2091,
    longitude: 113.9160,
    region: 'Kalimantan',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-banjarmasin',
    name: 'KPwBI Provinsi Kalimantan Selatan',
    city: 'Banjarmasin',
    provinceId: 'ID-KS',
    latitude: -3.3243,
    longitude: 114.5916,
    region: 'Kalimantan',
    isKorwil: true,
    category: 'korwil',
  },
  {
    id: 'kpwbi-samarinda',
    name: 'KPwBI Provinsi Kalimantan Timur',
    city: 'Samarinda',
    provinceId: 'ID-KI',
    latitude: -0.5034,
    longitude: 117.1471,
    region: 'Kalimantan',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-balikpapan',
    name: 'KPwBI Balikpapan',
    city: 'Balikpapan',
    provinceId: 'ID-KI',
    latitude: -1.2721,
    longitude: 116.8293,
    region: 'Kalimantan',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-tarakan',
    name: 'KPwBI Provinsi Kalimantan Utara',
    city: 'Tarakan',
    provinceId: 'ID-KU',
    latitude: 3.3087,
    longitude: 117.5913,
    region: 'Kalimantan',
    isKorwil: false,
    category: 'kpw',
  },

  // ═══════════════════════════════════════════════════════
  // Wilayah Koordinasi Bali & Nusa Tenggara (Korwil: Denpasar)
  // ═══════════════════════════════════════════════════════
  {
    id: 'kpwbi-denpasar',
    name: 'KPwBI Provinsi Bali',
    city: 'Denpasar',
    provinceId: 'ID-BA',
    latitude: -8.6757,
    longitude: 115.2285,
    region: 'Bali & Nusa Tenggara',
    isKorwil: true,
    category: 'korwil',
  },
  {
    id: 'kpwbi-mataram',
    name: 'KPwBI Provinsi Nusa Tenggara Barat',
    city: 'Mataram',
    provinceId: 'ID-NB',
    latitude: -8.5831,
    longitude: 116.1026,
    region: 'Bali & Nusa Tenggara',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-kupang',
    name: 'KPwBI Provinsi Nusa Tenggara Timur',
    city: 'Kupang',
    provinceId: 'ID-NT',
    latitude: -10.1585,
    longitude: 123.5855,
    region: 'Bali & Nusa Tenggara',
    isKorwil: false,
    category: 'kpw',
  },

  // ═══════════════════════════════════════════════════════
  // Wilayah Koordinasi Sulawesi, Maluku, & Papua (Korwil: Makassar)
  // ═══════════════════════════════════════════════════════
  {
    id: 'kpwbi-manado',
    name: 'KPwBI Provinsi Sulawesi Utara',
    city: 'Manado',
    provinceId: 'ID-SA',
    latitude: 1.4646,
    longitude: 124.8499,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-gorontalo',
    name: 'KPwBI Provinsi Gorontalo',
    city: 'Gorontalo',
    provinceId: 'ID-GO',
    latitude: 0.5428,
    longitude: 123.0583,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-palu',
    name: 'KPwBI Provinsi Sulawesi Tengah',
    city: 'Palu',
    provinceId: 'ID-ST',
    latitude: -0.8953,
    longitude: 119.8519,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-mamuju',
    name: 'KPwBI Provinsi Sulawesi Barat',
    city: 'Mamuju',
    provinceId: 'ID-SR',
    latitude: -2.6841,
    longitude: 118.8770,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-kendari',
    name: 'KPwBI Provinsi Sulawesi Tenggara',
    city: 'Kendari',
    provinceId: 'ID-SG',
    latitude: -3.9723,
    longitude: 122.5834,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-makassar',
    name: 'KPwBI Provinsi Sulawesi Selatan',
    city: 'Makassar',
    provinceId: 'ID-SN',
    latitude: -5.1384,
    longitude: 119.4109,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: true,
    category: 'korwil',
  },
  {
    id: 'kpwbi-ternate',
    name: 'KPwBI Provinsi Maluku Utara',
    city: 'Ternate',
    provinceId: 'ID-MU',
    latitude: 0.7891,
    longitude: 127.3855,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-ambon',
    name: 'KPwBI Provinsi Maluku',
    city: 'Ambon',
    provinceId: 'ID-MA',
    latitude: -3.6961,
    longitude: 128.1832,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-manokwari',
    name: 'KPwBI Provinsi Papua Barat',
    city: 'Manokwari',
    provinceId: 'ID-PB',
    latitude: -0.8660,
    longitude: 134.0760,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'kpwbi-jayapura',
    name: 'KPwBI Provinsi Papua',
    city: 'Jayapura',
    provinceId: 'ID-PA',
    latitude: -2.5369,
    longitude: 140.7107,
    region: 'Sulawesi, Maluku, & Papua',
    isKorwil: false,
    category: 'kpw',
  },
  {
    id: 'drc-sinergi-karawang',
    name: 'Gedung Sinergi — Data Center Bank Indonesia',
    city: 'Karawang',
    provinceId: 'ID-JB',
    latitude: -6.3215,
    longitude: 107.3381,
    region: 'Jawa',
    isKorwil: false,
    category: 'dc',
  },
];

/** Wilayah Koordinasi region names */
export const KPWBI_REGIONS = [
  'Sumatera',
  'Jawa',
  'Kalimantan',
  'Bali & Nusa Tenggara',
  'Sulawesi, Maluku, & Papua',
];
